### ISSUE TITLE
Missing requirements.txt file.

### ISSUE THREAD

**Issue by pjhampton** [Sea-of-BTC/Bitcoin-Trading-Client#5]
I propose that future development is approached within an environment such as VirtaulEnv. This will allow developers to contribute to the project without install memory intensive libraries such as pandas. As a result, we should implement a requirements.txt file by running the following command:

`$ pip freeze > requirements.txt`

This will make it easier for developers to get involved - I think. I can assign myself to this task.

**Comment by Sea-of-BTC** [comment]
Where are you wanting me to run that command? Tried it on the git client,
but I do not use pip on my machine. Cannot I just create the
requirements.txt file as I usually do?

I greatly appreciate your help with all of this. Never collaborated before,
a lot to learn.

-Harrison

**Comment by pjhampton** [comment]
No point running it on your machine, we need to isolate the development environment so people can set it up in less than a minute. I just added one there, but I recommend that you always develop in a virtual environment - will make your life much easier :-)
